### ISSUE TITLE
Window titles cover application icons

### ISSUE THREAD

**Issue by pesader** [G-dH/overview-feature-pack#1]
Hi there!

First of all, thanks for developing this extension! I've been using it daily ever since you announced it on [r/gnome](https://www.reddit.com/r/gnome/comments/vx9pup/ofp_overview_feature_pack_my_new_extension_that/).

I've noticed the window titles cover the icons when "Move titles into windows" is toggled on. Since I find the icons very important to tell windows apart at glance, I think it could be interesting to move the titles further up. Like so:

https://user-images.githubusercontent.com/65264536/199821073-b5d06722-3708-4d79-b8dc-1ab46ccdc3cf.mp4

I can make a PR with this (very small) change if you like it :)

**Comment by G-dH** [comment]
Hi, thanks for the feedback. The weak point in my title position calculation is the estimated label height, which should work for the default theme and font size on Ubuntu and Fedora. The actual height of the label is not available at that time, so the fix must move the calculation after the label is allocated and read the allocated height.

**Comment by pesader** [comment]
I made the recording above after changing the source code of the installed extension (in `~/.local/share/gnome-shell/extensions`). All I did was changing the number that multiplied `WindowPreview.ICON_SIZE`.

![old function](https://user-images.githubusercontent.com/65264536/200173877-2fec6864-8c6b-4135-ba8f-89ad339780f7.png)

However, I cloned the repo and it looks like this part of the code has been changed.

![image](https://user-images.githubusercontent.com/65264536/200174021-7788aa0c-b13d-4ed9-8e66-5369ed5ead2d.png)

I'll try to figure out how to do the same thing in the new version of the code, then submit a PR for review :)

**Comment by pesader** [comment]
![image](https://user-images.githubusercontent.com/65264536/200175129-ac94ab1a-f7da-4b53-8b24-36f64dfa099b.png)

Just installed the extension from the repo and it seems this is already fixed! Version 2.0 is looking great, by the way.

**Comment by G-dH** [comment]
I saw that someone has forked the repository and thought it was you, so I expected that you have the latest version installed. The change has been made to include the actual size of an app icon, which can be resized, not due to label misalignment.

The current repository version is not ready for release yet, but should be usable. Feel free to report bugs.
