### ISSUE TITLE
odd issue

### ISSUE THREAD

**Issue by mac-a-r0ni** [G-dH/overview-feature-pack#2]
The settings of extension overview-feature-pack@G-dH.github.com had an error:
```
TypeError: this.options[option] is undefined
```

Stack trace:
```
get@/home/jbl/.local/share/gnome-shell/extensions/overview-feature-pack@G-dH.github.com/settings.js:91:45
_connectComboBox@/home/jbl/.local/share/gnome-shell/extensions/overview-feature-pack@G-dH.github.com/prefs.js:767:36
getRowWidget@/home/jbl/.local/share/gnome-shell/extensions/overview-feature-pack@G-dH.github.com/prefs.js:746:22
_getDashOptionList@/home/jbl/.local/share/gnome-shell/extensions/overview-feature-pack@G-dH.github.com/prefs.js:216:21
init@/home/jbl/.local/share/gnome-shell/extensions/overview-feature-pack@G-dH.github.com/prefs.js:54:25
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:24:25
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```
I'm unsure if this issue is created by me, my install, or something else entirely. OFP did work on gnome 43 previously, after some updates to my system, I'm getting this error when trying to view the settings. Previously, it had disabled the extension, but it does appear to work as of installing the latest git today. I just can't configure anything, it seems.

Running all the latest 43.1 updates, compiled by hand on Slackware.

**Comment by G-dH** [comment]
Thanks for the report, I forgot to push the fix to GitHub. Version 2 is still in a 'work in progress' state.

**Comment by mac-a-r0ni** [comment]
oh no problem, I've ran it straight from git for a while (since I found a mention of it from you on reddit). I wasn't aware until recently there was even a released version! (But it didn't have a feature I'm accustomed to).
Thanks for the fix!
