### ISSUE TITLE
Divide features into different extension packs

### ISSUE THREAD

**Issue by vollowx** [G-dH/overview-feature-pack#3]
Could you please divide the features into different extension packs?

For example, I just want to custom the cols and rows of the app grid but any other features (of course they are really nice, just I don't need them, and also they will conflict with some other extensions such as Just Perfection, Dash to Dock, Unite on my computer with my config).

**Comment by vollowx** [comment]
At least please divide the features about the dock. It can't work with Dash to Dock.

**Comment by G-dH** [comment]
I don't see any conflict with DtD if all non-AppGrid OFP features are disabled, except the secondary button click on Show Apps icon, which is a bug. In general, OFP should only apply overrides needed for enabled options. Btw DtD is a pain in the ass for me, I don't need it, I've developed better window navigation, but I have to waste so much time to keep my extensions compatible with it :)

**Comment by G-dH** [comment]
@huge-pancake I would appreciate proper bug report, I care about compatibility with popular extensions and I'm testing both extensions you mentioned.

**Comment by vollowx** [comment]
Thanks, in fact they run well together now :P
