### ISSUE TITLE
Feature request: Always show Workspace labels in overview mode

### ISSUE THREAD

**Issue by xakraz** [G-dH/overview-feature-pack#4]
Hi @G-dH  👋🏻 !

Many thanks for your extension 🙏🏻 

Would it be possible to always display the Workspace's label in the overview mode?
A bit as MacOS does?

![](https://support.apple.com/library/content/dam/edam/applecare/images/de_DE/macos/Catalina/macos-catalina-mission-control-remove-space.jpg)

**Comment by G-dH** [comment]
Hi, this extension targets the default GNOME overview which has workspace thumbnails too small to fit labels. Try my [V-Shell](https://github.com/G-dH/vertical-workspaces) extension that offers what you're asking for and much more.
