### ISSUE TITLE
Remember workspace where windows were put when you switch between dual and single external monitor setup

### ISSUE THREAD

**Issue by jockep123** [G-dH/overview-feature-pack#7]
When you have remote working possibility with e.g. one external screen at home and two at work the location of the windows should be remembered for both setups. Today it is not.

**Comment by G-dH** [comment]
I'm sorry, window management is not the purpose of this extension.

**Comment by jockep123** [comment]
Can you then recommend an extension that do fix this problem then?

mån 4 sep. 2023 kl. 12:07 skrev G-dH ***@***.***>:

**Comment by G-dH** [comment]
Unfortunately, I'm not aware of such an extension.
