### ISSUE TITLE
Search results order

### ISSUE THREAD

**Issue by inwaar** [G-dH/overview-feature-pack#8]
Hi @G-dH and thanks for that extension, I've just ran into it and it's pity I didn't find it before :-)

One thing that makes it less productive is that the first search result that is focused is the web search:
![Screenshot from 2023-09-27 10-58-00](https://github.com/G-dH/overview-feature-pack/assets/3331076/6f3c63f0-4110-4b7c-942e-d373f07b7fc4)

Is there a way to make `Open Windows` the first focused? Or maybe just turn off the `Web` when `wq:` (space) is used?

**Comment by G-dH** [comment]
I'm sorry, this extension is not currently maintained but most of its features are available in the [V-Shell](https://github.com/G-dH/vertical-workspaces) extension. In the V-Shell you can activate only the window search provider by clicking on the icon in the dash, or by pressing the _Space_ key in the overview when search is not active.

**Comment by inwaar** [comment]
Oh, that one looks even more promising, thanks for those two extensions!
